#!/bin/bash

if [ "$#" -ne 1 ]; then
    echo "Usage: $0 <docker/compose/ls> "
    exit 1
fi

PROMPT="$1"

# if [ "$PROMPT" != "docker" ] && [ "$PROMPT" != "compose" ] && && [ "$PROMPT" != "ls" ]; then
    # echo "Error : $PROMPT. <docker/compose>"
    # exit 2
# fi

if [ "$PROMPT" = "docker" ]; then
    sudo apt update
    sudo apt upgrade -y
    sudo apt install apt-transport-https ca-certificates curl software-properties-common lsb-release -y
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
    sudo apt update
    sudo apt install docker-ce docker-ce-cli containerd.io -y
    docker --version
    exit 0
fi

if [ "$PROMPT" = "compose" ]; then
    sudo apt update
    sudo apt upgrade -y
    DOCKER_COMPOSE_VERSION=$(curl -s https://api.github.com/repos/docker/compose/releases/latest | grep tag_name | cut -d '"' -f 4)
    sudo curl -L "https://github.com/docker/compose/releases/download/$DOCKER_COMPOSE_VERSION/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
    sudo chmod +x /usr/local/bin/docker-compose
    sudo apt update
    docker-compose --version
    exit 0
fi

if [ "$PROMPT" = "ls" ]; then
    printf "\033[1;32m"
    docker ps -a

    printf "\033[1;33m"
    docker image ls

    printf "\033[1;34m"
    docker volume ls

    printf "\033[1;35m"
    docker network ls

    printf "\033[0m\n"
    exit 0
fi

# sudo usermod -aG docker $USER